# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ce04f82cd5d914e39836d731e1aa02b030d7f359e756642763e8c16380672609f69956dce2a6d2799c99e2201d4f4eaefc4e47e3c3b515247f8c0deceee0029

test:
  secret_key_base: ef98004e631d8b5ba3ac876ab732fbcd1c69feb2904f70139bc4e13bf7b569da22043afd9245cd8cabcb8371e4866f1dec3168f440fa538652d6243b4b7c6b30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
